resources:
  - name: spring-boot-service
    type: git
    source:
      uri: https://github.com/n4smh/test
      branch: main

  - name: spring-boot-service-docker-repository
    type: docker-image
    source:
      username: n4smh
      password: tasveer@dvG12
      repository: n4smh/hello-java2

jobs:
  - name: test
    public: true

    plan:
      - get: spring-boot-service
        trigger: true
      - task: mvn-test
        file: "spring-boot-service/concourse_ci/tasks/maven-test.yaml"

  - name: package
    public: true
    serial: true
    plan:
      - get: spring-boot-service
        trigger: true
        passed: [test]
      - task: mvn-package
        file: "spring-boot-service/concourse_ci/tasks/maven-package.yaml"
      - put: spring-boot-service-docker-repository
        params:
          build: spring-boot-service-out