---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.6.0-jdk-8-alpine

inputs:
  - name: spring-boot-service

run:
  path: ls
  args: ["-la", "spring-boot-service/DockerSample"]
outputs:
  - name: spring-boot-service-out
    path: spring-boot-service/DockerSample