---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.6.0-jdk-8-alpine

inputs:
  - name: spring-boot-service-out

run:
  path: /bin/sh
  args: ["spring-boot-service/concourse_ci/tasks/sample.sh"]
    
outputs:
  - name: spring-boot-service-out1
    path: spring-boot-service-out